#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &

MAVEN_REPO=$OPENSHIFT_BUILD_DEPENDENCIES_DIR/maven-repository
SOURCE_DIR=$OPENSHIFT_REPO_DIR
LOG_DIR=$OPENSHIFT_HOMEDIR/diy-0.1/logs

export MAVEN_OPTS="-Dmaven.repo.local=$MAVEN_REPO"

cd $OPENSHIFT_REPO_DIR
mvn clean install -DskipTests
nohup sh weboo-webapp/target/bin/webapp > $LOG_DIR/server.log 2>&1 &

