#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &

env

export REPO=$OPENSHIFT_HOMEDIR/.m2/repository

cd $OPENSHIFT_REPO_DIR
mvn clean install -DskipTests
nohup sh weboo-webapp/target/bin/webapp > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &

