web:
#  image: 188.226.158.138:32768/jzxweboo_web
  build: ./docker/app-node
  command: bash /start.sh weboo-webapp/target/bin/webapp
  ports:
   - "8080"
  volumes:
   - .:/code
lb:
#  image: 188.226.158.138:32768/jzxweboo_lb 
  build: ./docker/load-balancer
  command: /start-haproxy
  ports:
   - "8080:8080"
  links:
   - web
  