web:
  build: ./docker/app-node
  command: sh weboo-webapp/target/bin/webapp
  ports:
   - "8080"
  volumes:
   - .:/code
lb:
  build: ./docker/load-balancer
  command: /start-haproxy
  ports:
   - "8080:8080"
  links:
   - web
  