#!/bin/bash

cat /etc/haproxy/haproxy.cfg.template > /etc/haproxy/haproxy.cfg

NODE_NUMBERS=$(env | grep ^WEB_ | grep PORT_8080_TCP= | cut -f 2 -d '_')
for node in $NODE_NUMBERS; do
	ADDRESS=$(eval echo "\$WEB_${node}_PORT_8080_TCP_ADDR")
	PORT=$(eval echo "\$WEB_${node}_PORT_8080_TCP_PORT")

	echo " " >> /etc/haproxy/haproxy.cfg
	echo "        server  app1_$node $ADDRESS:$PORT cookie app1inst$node check inter 2000 rise 2 fall 5" >> /etc/haproxy/haproxy.cfg
done


haproxy -f /etc/haproxy/haproxy.cfg
