#!/bin/bash

set -eux

juju-log "Building application with Maven2 from $(pwd)"

./hooks/stop
mvn --batch-mode install -Pcloudfoundry -DskipTests

juju-log "Starting application in $(pwd)"
nohup sh weboo-webapp/target/bin/webapp > server.log 2>&1 &

open-port 8080
